require('dotenv').config();

import { defineConfig } from 'orval';

export default defineConfig({
  api_public: {
    output: {
      // mode: 'tags-split',
      workspace: 'src/api_public',
      target: 'api.ts',
      schemas: '../api_models',
      baseUrl: "http://localhost:8000",
      // client: 'fetch',
      mock: true,
      prettier: true,
      override: {
        header: (info): string[] => [
          `Alpaca API specification generated by orval. Check [orval.config.ts] for more details.`,
          `Do not edit manually.`,
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
        ],
      },
    },
    input: {
      validation: true,
      target: `http://localhost:8000/openapi.json`,
    },
  },

});
