/**
 * Alpaca API specification generated by orval. Check [orval.config.ts] for more details.
 * Do not edit manually.
 * OpenAPI spec version: 0.1.0
 */
import type { ApiGenerateNoteResponseError } from "./apiGenerateNoteResponseError";
import type { ApiGenerateNoteResponseGeneratedNote } from "./apiGenerateNoteResponseGeneratedNote";

export interface ApiGenerateNoteResponse {
  error?: ApiGenerateNoteResponseError;
  generated_note?: ApiGenerateNoteResponseGeneratedNote;
}
