/**
 * Alpaca API specification generated by orval. Check [orval.config.ts] for more details.
 * Do not edit manually.
 * OpenAPI spec version: 0.1.0
 */

export interface ApiSaveNoteRequest {
  note: string;
  therapist_id: string;
}
