/**
 * Alpaca API specification generated by orval. Check [orval.config.ts] for more details.
 * Do not edit manually.
 * OpenAPI spec version: 0.1.0
 */
import type { ApiSaveNoteResponseError } from "./apiSaveNoteResponseError";

export interface ApiSaveNoteResponse {
  error?: ApiSaveNoteResponseError;
  success: boolean;
}
